'use strict';
// i18n for everything the companions say. Six languages: en zh es ja ko de.
// Every non-English table spreads EN first, so a missing key can never crash.
// Per-pet voices: sounds (bubble chatter) / barkWord (action fx) / ackByPet.

const EN = {
  typing: 'typing sth? 👀',
  cheer: 'Go Claude go!',
  bigburn: 'what a burn!',
  rest: h => `${h}h of grinding — take a water break!`,
  almostLv: lv => `almost Lv.${lv}, push!`,
  levelUp: lv => `Lv.${lv}!!`,
  chatter: ['many bugs today?', 'pet me', 'coding = burning money', 'time to commit?', 'that rm looked confident'],
  sounds: { dog: 'woof!', owl: 'hoo hoo!', pig: 'oink!', cow: 'moo!', spider: 'tap tap~', seal: 'arf arf!' },
  barkWord: { dog: 'Woof!', owl: 'Hoot!', pig: 'Oink!', cow: 'Moo!', spider: '*tap*', seal: 'Arf!' },
  // /talktopet acks
  ackByPet: { dog: 'woof woof!', owl: 'hoo! hoo!', pig: 'oink oink!', cow: 'moo moo!', spider: '*taps the web*', seal: 'arf!' },
  ackMute: '...(nods quietly)',
  ackUnmute: 'back online!!',
  ackSleep: 'Zzz...',
  ackSit: 'sitting nicely!',
  ackJump: 'boing boing!!',
  ackBall: 'BALL!!!',
  ackZoom: 'FULL SPEED!!',
  ackEat: 'nom nom time!',
  ackFree: 'freedom!!',
  // CLI·BACKYARD ui
  uiSub: 'choose what lives in your terminal',
  uiPet: 'pet       — your terminal pet',
  uiYard: 'backyard  — scenes & decorations',
  uiBadges: 'badges    — achievements & rewards',
  uiLang: 'language',
  uiQuit: '[q] quit',
  uiPetHint: 'press 1-6 to adopt · [esc] back',
  uiYardHint: 'press 1-6 to toggle · [esc] back',
  uiBadgeHint: 'press number: claim its gift / pin to the bar',
  uiYardNote1: 'scenes replace the pet; ambient pieces stack with anything',
  uiSceneTag: 'scene',
  uiAmbientTag: 'ambient',
  uiActive: '✓ active',
  uiOff: 'off',
  uiInBar: '✓ in the bar',
  uiBadgeTag: 'badge',
  uiAdopted: name => `${name} moved into your bar!`,
  species: { dog: 'dog', owl: 'owl', pig: 'pig', cow: 'cow', spider: 'spider', seal: 'seal' },
  // badges
  uiBadgeClaimed: 'claimed',
  uiBadgePinned: 'pinned to bar',
  uiBadgeReady: 'CLAIMABLE — gift waiting!',
  uiBadgeLockedH: n => `locked · ${n}h`,
  bbWinPet: (name, sp) => `🎁 ${name} the ${sp} joins your backyard!!`,
  bbWinDeco: name => `🎁 ${name} is now yours — find it in backyard!`,
  bbEmpty: 'badge claimed — its gift is already home 🎉',
  uiBadgePinnedMsg: name => `${name} now shows in your status bar`,
  uiBadgeUnpinnedMsg: 'badge unpinned from the bar',
  uiBadgeNotYet: 'not earned yet — keep grinding',
  // home footer
  ftGrind: h => `${h}h grinding`,
  ftWeekLeft: p => `weekly left ${p}%`,
};

const ZH = {
  ...EN,
  typing: '在打字? 👀',
  cheer: 'Claude 加油!',
  bigburn: '这波烧得漂亮!',
  rest: h => `肝了${h}小时了, 起来喝口水!`,
  almostLv: lv => `快升 Lv.${lv} 了, 冲!`,
  levelUp: lv => `Lv.${lv} 啦!!`,
  chatter: ['今天 bug 多吗?', '摸摸我', '写代码就是烧钱', '该 commit 了吧', '我看你刚才 rm 得很自信'],
  sounds: { dog: '汪!', owl: '咕咕!', pig: '哼哼!', cow: '哞~', spider: '嗒嗒~', seal: '嗷呜!' },
  barkWord: { dog: '汪!', owl: '咕!', pig: '哼!', cow: '哞!', spider: '*嗒*', seal: '嗷!' },
  ackByPet: { dog: '汪汪!', owl: '咕咕!', pig: '哼哼!', cow: '哞哞!', spider: '*拨了拨网*', seal: '嗷呜!' },
  ackMute: '……(默默点头)',
  ackUnmute: '我回来啦!!',
  ackSleep: 'Zzz……',
  ackSit: '乖乖坐好!',
  ackJump: '跳跳跳!!',
  ackBall: '球球!!!',
  ackZoom: '全速前进!!',
  ackEat: '开饭! nom nom',
  ackFree: '自由啦!!',
  uiSub: '选择住进你终端里的东西',
  uiPet: 'pet       — 终端宠物',
  uiYard: 'backyard  — 场景和装饰',
  uiBadges: 'badges    — 成就和奖励',
  uiLang: 'language',
  uiQuit: '[q] 退出',
  uiPetHint: '按 1-6 领养 · [esc] 返回',
  uiYardHint: '按 1-6 开关 · [esc] 返回',
  uiBadgeHint: '按数字: 领取奖励 / 别到状态栏',
  uiYardNote1: '场景会替换宠物; 氛围装饰可以任意叠加',
  uiSceneTag: '场景',
  uiAmbientTag: '氛围',
  uiActive: '✓ 使用中',
  uiOff: '未启用',
  uiInBar: '✓ 在栏里',
  uiBadgeTag: '徽章',
  uiAdopted: name => `${name} 搬进你的状态栏啦!`,
  species: { dog: '狗', owl: '猫头鹰', pig: '猪', cow: '奶牛', spider: '蜘蛛', seal: '海豹' },
  uiBadgeClaimed: '已领取',
  uiBadgePinned: '已别到状态栏',
  uiBadgeReady: '可领取 — 奖励在等你!',
  uiBadgeLockedH: n => `未解锁 · 需 ${n}h`,
  bbWinPet: (name, sp) => `🎁 奖励到手: ${sp} ${name} 入住你的后院!!`,
  bbWinDeco: name => `🎁 奖励到手: ${name} — 去 backyard 里摆上吧!`,
  bbEmpty: '徽章到手 — 它的奖励你已经有了 🎉',
  uiBadgePinnedMsg: name => `${name} 已显示在状态栏`,
  uiBadgeUnpinnedMsg: '已从状态栏取下徽章',
  uiBadgeNotYet: '还没达成 — 接着肝',
  ftGrind: h => `肝了 ${h} 小时`,
  ftWeekLeft: p => `本周额度剩 ${p}%`,
};

const ES = {
  ...EN,
  typing: '¿escribiendo algo? 👀',
  cheer: '¡Vamos Claude!',
  bigburn: '¡qué quemada!',
  rest: h => `${h}h dándole — ¡toma agua!`,
  almostLv: lv => `casi Lv.${lv}, ¡dale!`,
  levelUp: lv => `¡¡Lv.${lv}!!`,
  chatter: ['¿muchos bugs hoy?', 'acaríciame', 'programar = quemar dinero', '¿hora de commit?', 'ese rm se veía muy seguro'],
  sounds: { dog: '¡guau!', owl: '¡uu uu!', pig: '¡oinc!', cow: '¡muu!', spider: 'tap tap~', seal: '¡arf arf!' },
  barkWord: { dog: '¡Guau!', owl: '¡Uu!', pig: '¡Oinc!', cow: '¡Muu!', spider: '*tap*', seal: '¡Arf!' },
  ackByPet: { dog: '¡guau guau!', owl: '¡uu! ¡uu!', pig: '¡oinc oinc!', cow: '¡muu muu!', spider: '*teje su red*', seal: '¡arf!' },
  ackMute: '...(asiente en silencio)',
  ackUnmute: '¡¡de vuelta!!',
  ackSit: '¡sentadito!',
  ackJump: '¡¡boing boing!!',
  ackBall: '¡¡¡PELOTA!!!',
  ackZoom: '¡¡A TODA VELOCIDAD!!',
  ackEat: '¡ñam ñam!',
  ackFree: '¡¡libertad!!',
  uiSub: 'elige qué vive en tu terminal',
  uiPet: 'pet       — tu mascota del terminal',
  uiYard: 'backyard  — escenas y decoraciones',
  uiBadges: 'badges    — logros y recompensas',
  uiPetHint: 'pulsa 1-6 para adoptar · [esc] volver',
  uiYardHint: 'pulsa 1-6 para alternar · [esc] volver',
  uiBadgeHint: 'pulsa número: reclamar el regalo / fijar en la barra',
  uiYardNote1: 'las escenas reemplazan a la mascota; lo ambiental se apila',
  uiSceneTag: 'escena',
  uiAmbientTag: 'ambiente',
  uiActive: '✓ activo',
  uiOff: 'off',
  uiInBar: '✓ en la barra',
  uiBadgeTag: 'insignia',
  uiAdopted: name => `¡${name} se mudó a tu barra!`,
  species: { dog: 'perro', owl: 'búho', pig: 'cerdo', cow: 'vaca', spider: 'araña', seal: 'foca' },
  uiBadgeClaimed: 'reclamada',
  uiBadgePinned: 'fijada en la barra',
  uiBadgeReady: '¡RECLAMABLE — regalo esperando!',
  uiBadgeLockedH: n => `bloqueada · ${n}h`,
  bbWinPet: (name, sp) => `🎁 ¡${name} (${sp}) llega a tu patio!!`,
  bbWinDeco: name => `🎁 ${name} ya es tuyo — ¡míralo en backyard!`,
  bbEmpty: 'insignia reclamada — ya tienes todos los premios 🎉',
  uiBadgePinnedMsg: name => `${name} ahora aparece en tu barra`,
  uiBadgeUnpinnedMsg: 'insignia quitada de la barra',
  uiBadgeNotYet: 'aún no — sigue dándole',
  ftGrind: h => `${h}h de esfuerzo`,
  ftWeekLeft: p => `queda ${p}% semanal`,
};

const JA = {
  ...EN,
  typing: '何か打ってる? 👀',
  cheer: 'Claude がんばれ!',
  bigburn: 'いい燃焼っぷり!',
  rest: h => `${h}時間も作業中 — 水分補給して!`,
  almostLv: lv => `もうすぐ Lv.${lv}, ファイト!`,
  levelUp: lv => `Lv.${lv} だ!!`,
  chatter: ['今日バグ多い?', 'なでて', 'コーディング = お金を燃やすこと', 'そろそろ commit?', 'さっきの rm、自信満々だったね'],
  sounds: { dog: 'ワン!', owl: 'ホーホー!', pig: 'ブヒ!', cow: 'モー!', spider: 'カタカタ~', seal: 'アウアウ!' },
  barkWord: { dog: 'ワン!', owl: 'ホー!', pig: 'ブヒ!', cow: 'モー!', spider: '*カタ*', seal: 'アウ!' },
  ackByPet: { dog: 'ワンワン!', owl: 'ホーホー!', pig: 'ブヒブヒ!', cow: 'モーモー!', spider: '*巣を鳴らした*', seal: 'アウ!' },
  ackMute: '……(静かにうなずく)',
  ackUnmute: 'ただいま!!',
  ackSit: 'おすわり!',
  ackJump: 'ぴょんぴょん!!',
  ackBall: 'ボール!!!',
  ackZoom: '全速力!!',
  ackEat: 'ごはんだ! もぐもぐ',
  ackFree: '自由だ!!',
  uiSub: 'ターミナルに住むものを選ぼう',
  uiPet: 'pet       — ターミナルのペット',
  uiYard: 'backyard  — シーンと装飾',
  uiBadges: 'badges    — 実績と報酬',
  uiPetHint: '1-6 で迎える · [esc] 戻る',
  uiYardHint: '1-6 で切替 · [esc] 戻る',
  uiBadgeHint: '数字キー: 報酬を受け取る / バーにピン留め',
  uiYardNote1: 'シーンはペットと入れ替わり; アンビエントは重ねられる',
  uiSceneTag: 'シーン',
  uiAmbientTag: 'アンビエント',
  uiActive: '✓ 使用中',
  uiOff: 'オフ',
  uiInBar: '✓ バーにいる',
  uiBadgeTag: 'バッジ',
  uiAdopted: name => `${name} がバーに引っ越してきた!`,
  species: { dog: '犬', owl: 'フクロウ', pig: 'ブタ', cow: 'ウシ', spider: 'クモ', seal: 'アザラシ' },
  uiBadgeClaimed: '受取済み',
  uiBadgePinned: 'バーにピン留め中',
  uiBadgeReady: '受け取れる — ギフトが待ってる!',
  uiBadgeLockedH: n => `ロック中 · ${n}h`,
  bbWinPet: (name, sp) => `🎁 ${sp}の ${name} が仲間入り!!`,
  bbWinDeco: name => `🎁 ${name} ゲット — backyard で飾ろう!`,
  bbEmpty: 'バッジ受取 — 景品はもう全部そろってる 🎉',
  uiBadgePinnedMsg: name => `${name} をステータスバーに表示中`,
  uiBadgeUnpinnedMsg: 'バッジをバーから外した',
  uiBadgeNotYet: 'まだ達成してない — 積み上げよう',
  ftGrind: h => `${h}時間 稼働`,
  ftWeekLeft: p => `週間残量 ${p}%`,
};

const KO = {
  ...EN,
  typing: '뭔가 치는 중? 👀',
  cheer: 'Claude 화이팅!',
  bigburn: '멋지게 태웠다!',
  rest: h => `${h}시간째 달리는 중 — 물 한잔 해요!`,
  almostLv: lv => `곧 Lv.${lv}, 가자!`,
  levelUp: lv => `Lv.${lv}!!`,
  chatter: ['오늘 버그 많아요?', '쓰다듬어 줘요', '코딩 = 돈 태우기', '슬슬 commit?', '아까 그 rm 자신만만하던데'],
  sounds: { dog: '멍멍!', owl: '부엉부엉!', pig: '꿀꿀!', cow: '음메~', spider: '톡톡~', seal: '아르프!' },
  barkWord: { dog: '멍!', owl: '부엉!', pig: '꿀!', cow: '음메!', spider: '*톡*', seal: '아릅!' },
  ackByPet: { dog: '멍멍!', owl: '부엉부엉!', pig: '꿀꿀!', cow: '음메음메!', spider: '*거미줄을 튕겼다*', seal: '아르프!' },
  ackMute: '...(조용히 끄덕)',
  ackUnmute: '다시 왔어요!!',
  ackSit: '얌전히 앉기!',
  ackJump: '폴짝폴짝!!',
  ackBall: '공!!!',
  ackZoom: '전속력!!',
  ackEat: '냠냠 시간!',
  ackFree: '자유다!!',
  uiSub: '터미널에 살 것을 골라요',
  uiPet: 'pet       — 터미널 펫',
  uiYard: 'backyard  — 씬과 장식',
  uiBadges: 'badges    — 업적과 보상',
  uiPetHint: '1-6 입양 · [esc] 뒤로',
  uiYardHint: '1-6 토글 · [esc] 뒤로',
  uiBadgeHint: '숫자 키: 보상 수령 / 바에 고정',
  uiYardNote1: '씬은 펫을 대체; 앰비언트는 자유롭게 겹침',
  uiSceneTag: '씬',
  uiAmbientTag: '앰비언트',
  uiActive: '✓ 사용 중',
  uiOff: '꺼짐',
  uiInBar: '✓ 바에 있음',
  uiBadgeTag: '배지',
  uiAdopted: name => `${name} 이(가) 바로 이사 왔어요!`,
  species: { dog: '강아지', owl: '부엉이', pig: '돼지', cow: '젖소', spider: '거미', seal: '물범' },
  uiBadgeClaimed: '수령함',
  uiBadgePinned: '바에 고정됨',
  uiBadgeReady: '수령 가능 — 선물이 기다려요!',
  uiBadgeLockedH: n => `잠김 · ${n}h`,
  bbWinPet: (name, sp) => `🎁 ${sp} ${name} 합류!!`,
  bbWinDeco: name => `🎁 ${name} 획득 — backyard에서 꾸며봐요!`,
  bbEmpty: '배지 수령 — 상품은 이미 다 모았어요 🎉',
  uiBadgePinnedMsg: name => `${name} 이(가) 상태바에 표시돼요`,
  uiBadgeUnpinnedMsg: '배지를 바에서 내렸어요',
  uiBadgeNotYet: '아직 멀었어요 — 계속 갈아넣기',
  ftGrind: h => `${h}시간 갈아넣음`,
  ftWeekLeft: p => `주간 잔여 ${p}%`,
};

const DE = {
  ...EN,
  typing: 'tippst du was? 👀',
  cheer: 'Los Claude los!',
  bigburn: 'was für ein Burn!',
  rest: h => `${h}h am Stück — trink mal Wasser!`,
  almostLv: lv => `fast Lv.${lv}, weiter!`,
  levelUp: lv => `Lv.${lv}!!`,
  chatter: ['viele Bugs heute?', 'streichel mich', 'Coden = Geld verbrennen', 'Zeit zu committen?', 'das rm sah sehr selbstsicher aus'],
  sounds: { dog: 'wuff!', owl: 'schuhu!', pig: 'oink!', cow: 'muh!', spider: 'tap tap~', seal: 'arf arf!' },
  barkWord: { dog: 'Wuff!', owl: 'Schuhu!', pig: 'Oink!', cow: 'Muh!', spider: '*tap*', seal: 'Arf!' },
  ackByPet: { dog: 'wuff wuff!', owl: 'schuhu!', pig: 'oink oink!', cow: 'muh muh!', spider: '*zupft am Netz*', seal: 'arf!' },
  ackMute: '...(nickt leise)',
  ackUnmute: 'wieder da!!',
  ackSit: 'brav gesessen!',
  ackJump: 'hüpf hüpf!!',
  ackBall: 'BALL!!!',
  ackZoom: 'VOLLGAS!!',
  ackEat: 'mampf mampf!',
  ackFree: 'Freiheit!!',
  uiSub: 'wähl, was in deinem Terminal wohnt',
  uiPet: 'pet       — dein Terminal-Haustier',
  uiYard: 'backyard  — Szenen & Deko',
  uiBadges: 'badges    — Erfolge & Belohnungen',
  uiPetHint: '1-6 adoptieren · [esc] zurück',
  uiYardHint: '1-6 umschalten · [esc] zurück',
  uiBadgeHint: 'Zahl drücken: Geschenk abholen / an die Bar pinnen',
  uiYardNote1: 'Szenen ersetzen das Tier; Ambientes stapeln sich frei',
  uiSceneTag: 'Szene',
  uiAmbientTag: 'Ambiente',
  uiActive: '✓ aktiv',
  uiOff: 'aus',
  uiInBar: '✓ in der Bar',
  uiBadgeTag: 'Abzeichen',
  uiAdopted: name => `${name} ist in deine Bar eingezogen!`,
  species: { dog: 'Hund', owl: 'Eule', pig: 'Schwein', cow: 'Kuh', spider: 'Spinne', seal: 'Robbe' },
  uiBadgeClaimed: 'eingelöst',
  uiBadgePinned: 'an der Bar',
  uiBadgeReady: 'EINLÖSBAR — Geschenk wartet!',
  uiBadgeLockedH: n => `gesperrt · ${n}h`,
  bbWinPet: (name, sp) => `🎁 ${name} die ${sp} zieht bei dir ein!!`,
  bbWinDeco: name => `🎁 ${name} gehört dir — schau in backyard!`,
  bbEmpty: 'Abzeichen eingelöst — alle Preise sind schon da 🎉',
  uiBadgePinnedMsg: name => `${name} steht jetzt in deiner Statusbar`,
  uiBadgeUnpinnedMsg: 'Abzeichen von der Bar genommen',
  uiBadgeNotYet: 'noch nicht — weiter grinden',
  ftGrind: h => `${h}h gegrindet`,
  ftWeekLeft: p => `Woche: ${p}% übrig`,
};

const LANGS = { en: EN, zh: ZH, es: ES, ja: JA, ko: KO, de: DE };
const LANG_ORDER = ['en', 'zh', 'es', 'ja', 'ko', 'de'];
const LANG_LABEL = { en: 'ENG', zh: '中文', es: 'ESP', ja: '日本語', ko: '한국어', de: 'DEU' };

function tr(state) { return LANGS[(state && state.lang)] || EN; }

// per-pet lookup helper: many ack strings are either a string or a pet map
function perPet(v, petId) { return typeof v === 'object' && v !== null ? (v[petId] || v.dog) : v; }

module.exports = { tr, perPet, LANGS, LANG_ORDER, LANG_LABEL, EN, ZH };
